<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'flash.message.success' => 'Süti beállítások el lettek mentve!',
    'hint.ads' => 'Ennek segítségével tudunk neked később az oldalunkkal kapcsolatos hirdetéseket megjeleníteni más weboldalakon.',
    'hint.behavior' => 'Ennek segítségével tudjuk mérni aktivitásod az oldalunkon.',
    'hint.performance' => 'Ennek segítésével tudjuk mérni az oldal látogatottságát és hirdetéseink teljesítményét.',
    'hint.session' => 'Egy webáruházban ennek segítségével lehet megkülönböztetni a kosaradban lévő termékeidet másokétól. Vagy bejelentkezés után ennek köszönhetően lehet  megkülönböztetni a többi bejelentkezett felhasználótól.',
    'hint.usage-helper' => 'Ilyen süti-ben tároljuk azt, hogy emlékezzen rád az oldal bejelentkezés után is. Illetve ennek az űrlapnak a beállításait is ilyen sütikben tároljuk, ha módosítottál valamit a kapcsolókon.',
    'input.allowed' => 'Engedélyezve',
    'input.disallowed' => 'Megtiltva',
    'label.ads' => 'Célzó és hirdetési sütik',
    'label.behavior' => 'Böngésző felhasználókat megkülönböztető, azonosító sütik',
    'label.performance' => 'Teljesítményt biztosító sütik',
    'label.session' => 'Munkamenet sütik',
    'label.usage-helper' => 'Használatot elősegítő sütik',
];
