<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'flash.message.success' => 'Süti beállítások el lettek mentve!',
    'hint.ads' => 'Ennek segítségével tudunk később az oldalunkkal kapcsolatos hirdetéseket megjeleníteni más weboldalakon.',
    'hint.behavior' => 'Ennek segítségével tudjuk mérni a látogatók aktivitását, amely információkat weboldalunk optimalizálására használunk fel.',
    'hint.statistics' => 'Ennek segítésével tudjuk mérni az oldal látogatottsági statisztikáját és hirdetéseink teljesítményét.',
    'hint.session' => 'Egy webáruházban ennek köszönhetően láthatja azt a terméket a kosarában amit választott és nem pedig egy másik felhasználó által összeválogatott termékeket.',
    'hint.social' => 'Közösségi oldalak widgetjei által használt cookie-k. Ilyen például a Facebook Page Plugin, Facebook Comments Widget vagy a Google Maps térkép is.',
    'hint.usage-helper' => 'Ennek segítségével tároljuk például ennek az űrlapnak a beállításait.',
    'input.allowed' => 'Be',
    'input.disallowed' => 'Ki',
    'label.ads' => 'Célzó és Hirdetési sütik',
    'label.behavior' => 'Viselkedést elemző sütik',
    'label.statistics' => 'Statisztikai sütik',
    'label.session' => 'Munkamenet sütik',
    'label.social' => 'Közösségi hálózatok sütijei',
    'label.usage-helper' => 'Használatot segítő sütik',
];
