<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Save' => 'Mentés',
    'form.error.session-is-required' => 'Munkamenet sütiket kötelező engedélyezni!',
    'form.error.usage-helper-is-required' => 'Használatot elősegítő sütiket kötelező engedélyezni, hogy el tudjuk tárolni ezeket a beállításokat!',
    'header' => 'Ez az oldal cookie-kat használ!',
    'allow' => 'Cookie-k engedélyezése',
    'deny' => 'Elutasítom',
    'dismiss' => 'Elfogadom!',
    'link' => 'Tudjon meg többet...',
    'message' => 'Ez a weboldal cookie-kat használ, hogy a lehető legjobb élményt nyújtsa honlapunkon.',
];
