<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'flash.message.success' => 'Les paramètres des cookies ont été mis à jour avec succès !',
    'hint.ads' => 'Cookies de remarketing, tels que le cookie de remarketing de Google AdWords.',
    'hint.behavior' => 'Cookies pour stocker les comportements liés à l\’utilisateur. Comme ce paramètre sous cette forme.',
    'hint.social' => 'Les cookies utilisés par les widgets de réseaux sociaux tels que les plug-ins de pages Facebook ou Google Maps.',
    'hint.statistics' => 'Cookies qui nous aident à mesurer les performances de ce site. Par exemple, suivre les conversions dans Google Analytics et Facebook. ',
    'hint.session' => 'Les cookies de session sont nécessaires pour distinguer les utilisateurs du site.',
    'hint.usage_helper' => 'Cookies pour stocker des informations comme la case à cocher "Mémoriser mes informations" sur les formulaires de connexion.',
    'input.allowed' => 'On',
    'input.disallowed' => 'Off',
    'label.ads' => 'Cookies publicitaires',
    'label.behavior' => 'Cookies de comportement',
    'label.statistics' => 'Cookies statistiques',
    'label.session' => 'Cookies de session',
    'label.social' => 'Cookies de réseaux sociaux',
    'label.usage_helper' => 'Cookies d\'assistance à l\'utilisation',
];
