<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'flash.message.success' => '¡La configuración de la cookie se actualizó con éxito!',
    'hint.ads' => 'Cookies de remarketing, como la cookie de remarketing de Google AdWords.',
    'hint.behavior' => 'Cookies para almacenar comportamientos relacionados con el usuario. Me gusta esta configuración en esta forma.',
    'hint.social' => 'Cookies que utilizan los widgets de las redes sociales como el complemento de la página de Facebook o Google Maps.',
    'hint.statistics' => 'Cookies que nos ayudan a medir el rendimiento de este sitio. Por ejemplo, el seguimiento de las conversiones en Google Analytics y Facebook.',
    'hint.session' => 'Las cookies de sesión son necesarias para distinguir a los usuarios en el sitio.',
    'hint.usage_helper' => 'Cookies para almacenar información como la casilla "Recordarme" en los formularios de inicio de sesión.',
    'input.allowed' => 'On',
    'input.disallowed' => 'Off',
    'label.ads' => 'Cookies de publicidad',
    'label.behavior' => 'Cookies de comportamiento',
    'label.statistics' => 'Cookies de estadística',
    'label.session' => 'Cookies de sesión',
    'label.social' => 'Cookies de redes sociales',
    'label.usage_helper' => 'Cookies de ayuda de uso',
];
