<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'flash.message.success' => 'Cookie settings are successfully updated!',
    'hint.ads' => 'Remarketing cookies, like Google AdWords remarketing cookie.',
    'hint.behavior' => 'Cookies to store user related behaviors. Like this setting in this form.',
    'hint.performance' => 'Cookies which helps us to measure the performance of this site. For example tracking conversions in Google Analytics and Facebook.',
    'hint.session' => 'Session cookies are required to distinguish users on the site.',
    'hint.usage-helper' => 'Cookies to store informations like "Remember me" checkbox on login forms.',
    'input.allowed' => 'Allowed',
    'input.disallowed' => 'Disallowed',
    'label.ads' => 'Ad cookies',
    'label.behavior' => 'Behavior cookies',
    'label.performance' => 'Performance cookies',
    'label.session' => 'Session cookies',
    'label.usage-helper' => 'Usage helper cookies',
];
